image: ruby:2.4

# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - bundle install
    - bundle exec jekyll build -d public --baseurl /slicing-pie
  artifacts:
    paths:
      - public
  only:
    - master # this job will affect only the 'master' branch
